[2021-05-15 20:48:25,157] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: airflow_tutorial_v01.sleep 2017-06-26T07:00:00+00:00 [queued]>
[2021-05-15 20:48:25,163] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: airflow_tutorial_v01.sleep 2017-06-26T07:00:00+00:00 [queued]>
[2021-05-15 20:48:25,163] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-15 20:48:25,163] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-05-15 20:48:25,163] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-15 20:48:25,168] {taskinstance.py:1089} INFO - Executing <Task(BashOperator): sleep> on 2017-06-26T07:00:00+00:00
[2021-05-15 20:48:25,169] {standard_task_runner.py:52} INFO - Started process 71091 to run task
[2021-05-15 20:48:25,176] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'airflow_tutorial_v01', 'sleep', '2017-06-26T07:00:00+00:00', '--job-id', '1834', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/Untitled.py', '--cfg-path', '/var/folders/tp/ft4rfkmn1kz3dyw8hlfz1dxw0000gn/T/tmp4mmk_0ab', '--error-file', '/var/folders/tp/ft4rfkmn1kz3dyw8hlfz1dxw0000gn/T/tmpr997hx1o']
[2021-05-15 20:48:25,178] {standard_task_runner.py:77} INFO - Job 1834: Subtask sleep
[2021-05-15 20:48:25,212] {logging_mixin.py:104} INFO - Running <TaskInstance: airflow_tutorial_v01.sleep 2017-06-26T07:00:00+00:00 [running]> on host 1.0.0.127.in-addr.arpa
[2021-05-15 20:48:25,243] {taskinstance.py:1281} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=airflow_tutorial_v01
AIRFLOW_CTX_TASK_ID=sleep
AIRFLOW_CTX_EXECUTION_DATE=2017-06-26T07:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2017-06-26T07:00:00+00:00
[2021-05-15 20:48:25,244] {bash.py:135} INFO - Tmp dir root location: 
 /var/folders/tp/ft4rfkmn1kz3dyw8hlfz1dxw0000gn/T
[2021-05-15 20:48:25,245] {bash.py:158} INFO - Running command: sleep 5
[2021-05-15 20:48:25,252] {bash.py:169} INFO - Output:
[2021-05-15 20:48:30,219] {local_task_job.py:174} WARNING - The recorded hostname 1.0.0.127.in-addr.arpa does not match this instance's hostname henrys-macbook-pro.local
[2021-05-15 20:48:30,228] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 71091
[2021-05-15 20:48:30,228] {taskinstance.py:1265} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-05-15 20:48:30,229] {bash.py:185} INFO - Sending SIGTERM signal to bash process group
[2021-05-15 20:48:30,234] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/harry/.local/share/virtualenvs/rugby_data_project_airflow-d2RAFQI6/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/Users/harry/.local/share/virtualenvs/rugby_data_project_airflow-d2RAFQI6/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/Users/harry/.local/share/virtualenvs/rugby_data_project_airflow-d2RAFQI6/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/Users/harry/.local/share/virtualenvs/rugby_data_project_airflow-d2RAFQI6/lib/python3.8/site-packages/airflow/operators/bash.py", line 171, in execute
    for raw_line in iter(self.sub_process.stdout.readline, b''):
  File "/Users/harry/.local/share/virtualenvs/rugby_data_project_airflow-d2RAFQI6/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1267, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2021-05-15 20:48:30,240] {taskinstance.py:1525} INFO - Marking task as UP_FOR_RETRY. dag_id=airflow_tutorial_v01, task_id=sleep, execution_date=20170626T070000, start_date=20210515T194825, end_date=20210515T194830
[2021-05-15 20:48:30,257] {process_utils.py:66} INFO - Process psutil.Process(pid=71096, status='terminated', started='20:48:25') (71096) terminated with exit code None
[2021-05-15 20:48:30,257] {process_utils.py:66} INFO - Process psutil.Process(pid=71091, status='terminated', exitcode=1, started='20:48:25') (71091) terminated with exit code 1
