[2021-05-17 09:12:47,704] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: matches_links.get_autumn_nations_cup_links 2021-04-24T10:00:00+00:00 [queued]>
[2021-05-17 09:12:47,708] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: matches_links.get_autumn_nations_cup_links 2021-04-24T10:00:00+00:00 [queued]>
[2021-05-17 09:12:47,708] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-17 09:12:47,708] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-05-17 09:12:47,708] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-17 09:12:47,713] {taskinstance.py:1089} INFO - Executing <Task(BashOperator): get_autumn_nations_cup_links> on 2021-04-24T10:00:00+00:00
[2021-05-17 09:12:47,715] {standard_task_runner.py:52} INFO - Started process 10406 to run task
[2021-05-17 09:12:47,721] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'matches_links', 'get_autumn_nations_cup_links', '2021-04-24T10:00:00+00:00', '--job-id', '7', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/matches_links/matches_links.py', '--cfg-path', '/var/folders/tp/ft4rfkmn1kz3dyw8hlfz1dxw0000gn/T/tmp5oly9jid', '--error-file', '/var/folders/tp/ft4rfkmn1kz3dyw8hlfz1dxw0000gn/T/tmpfb4snrzv']
[2021-05-17 09:12:47,724] {standard_task_runner.py:77} INFO - Job 7: Subtask get_autumn_nations_cup_links
[2021-05-17 09:12:47,758] {logging_mixin.py:104} INFO - Running <TaskInstance: matches_links.get_autumn_nations_cup_links 2021-04-24T10:00:00+00:00 [running]> on host 1.0.0.127.in-addr.arpa
[2021-05-17 09:12:47,781] {taskinstance.py:1281} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=matches_links
AIRFLOW_CTX_TASK_ID=get_autumn_nations_cup_links
AIRFLOW_CTX_EXECUTION_DATE=2021-04-24T10:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=backfill__2021-04-24T10:00:00+00:00
[2021-05-17 09:12:47,781] {bash.py:135} INFO - Tmp dir root location: 
 /var/folders/tp/ft4rfkmn1kz3dyw8hlfz1dxw0000gn/T
[2021-05-17 09:12:47,782] {bash.py:158} INFO - Running command: Rscript /Users/harry/rugby_data_project_airflow/R/scripts/create_matches_table.R  https://www.rugbypass.com/autumn-nations-cup/matches/
[2021-05-17 09:12:47,788] {bash.py:169} INFO - Output:
[2021-05-17 09:12:49,257] {bash.py:173} INFO - ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.0 ──
[2021-05-17 09:12:49,262] {bash.py:173} INFO - ✔ ggplot2 3.3.3     ✔ purrr   0.3.3
[2021-05-17 09:12:49,262] {bash.py:173} INFO - ✔ tibble  3.0.4     ✔ dplyr   1.0.2
[2021-05-17 09:12:49,263] {bash.py:173} INFO - ✔ tidyr   1.1.2     ✔ stringr 1.4.0
[2021-05-17 09:12:49,263] {bash.py:173} INFO - ✔ readr   1.3.1     ✔ forcats 0.5.0
[2021-05-17 09:12:49,337] {bash.py:173} INFO - ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
[2021-05-17 09:12:49,338] {bash.py:173} INFO - ✖ dplyr::filter() masks stats::filter()
[2021-05-17 09:12:49,338] {bash.py:173} INFO - ✖ dplyr::lag()    masks stats::lag()
[2021-05-17 09:12:49,347] {bash.py:173} INFO - 
[2021-05-17 09:12:49,347] {bash.py:173} INFO - Attaching package: ‘lubridate’
[2021-05-17 09:12:49,348] {bash.py:173} INFO - 
[2021-05-17 09:12:49,348] {bash.py:173} INFO - The following objects are masked from ‘package:base’:
[2021-05-17 09:12:49,348] {bash.py:173} INFO - 
[2021-05-17 09:12:49,348] {bash.py:173} INFO -     date, intersect, setdiff, union
[2021-05-17 09:12:49,349] {bash.py:173} INFO - 
[2021-05-17 09:12:49,350] {bash.py:173} INFO - Loading required package: xml2
[2021-05-17 09:12:49,357] {bash.py:173} INFO - 
[2021-05-17 09:12:49,357] {bash.py:173} INFO - Attaching package: ‘rvest’
[2021-05-17 09:12:49,357] {bash.py:173} INFO - 
[2021-05-17 09:12:49,358] {bash.py:173} INFO - The following object is masked from ‘package:purrr’:
[2021-05-17 09:12:49,358] {bash.py:173} INFO - 
[2021-05-17 09:12:49,358] {bash.py:173} INFO -     pluck
[2021-05-17 09:12:49,359] {bash.py:173} INFO - 
[2021-05-17 09:12:49,359] {bash.py:173} INFO - The following object is masked from ‘package:readr’:
[2021-05-17 09:12:49,359] {bash.py:173} INFO - 
[2021-05-17 09:12:49,359] {bash.py:173} INFO -     guess_encoding
[2021-05-17 09:12:49,360] {bash.py:173} INFO - 
[2021-05-17 09:12:49,365] {bash.py:173} INFO - [1] "Getting autumn_nations_cup links"
[2021-05-17 09:12:51,678] {bash.py:173} INFO - [1] "autumn_nations_cup saved"
[2021-05-17 09:12:51,679] {bash.py:173} INFO - Error: unexpected '}' in "}"
[2021-05-17 09:12:51,679] {bash.py:173} INFO - Execution halted
[2021-05-17 09:12:51,695] {bash.py:177} INFO - Command exited with return code 1
[2021-05-17 09:12:51,701] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/harry/.local/share/virtualenvs/rugby_data_project_airflow-d2RAFQI6/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/Users/harry/.local/share/virtualenvs/rugby_data_project_airflow-d2RAFQI6/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/Users/harry/.local/share/virtualenvs/rugby_data_project_airflow-d2RAFQI6/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/Users/harry/.local/share/virtualenvs/rugby_data_project_airflow-d2RAFQI6/lib/python3.8/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-05-17 09:12:51,703] {taskinstance.py:1525} INFO - Marking task as UP_FOR_RETRY. dag_id=matches_links, task_id=get_autumn_nations_cup_links, execution_date=20210424T100000, start_date=20210517T081247, end_date=20210517T081251
[2021-05-17 09:12:51,750] {local_task_job.py:146} INFO - Task exited with return code 1
[2021-05-17 09:18:41,175] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: matches_links.get_autumn_nations_cup_links 2021-04-24T10:00:00+00:00 [queued]>
[2021-05-17 09:18:41,179] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: matches_links.get_autumn_nations_cup_links 2021-04-24T10:00:00+00:00 [queued]>
[2021-05-17 09:18:41,179] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-17 09:18:41,179] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-05-17 09:18:41,179] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-17 09:18:41,184] {taskinstance.py:1089} INFO - Executing <Task(BashOperator): get_autumn_nations_cup_links> on 2021-04-24T10:00:00+00:00
[2021-05-17 09:18:41,186] {standard_task_runner.py:52} INFO - Started process 14408 to run task
[2021-05-17 09:18:41,191] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'matches_links', 'get_autumn_nations_cup_links', '2021-04-24T10:00:00+00:00', '--job-id', '7', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/matches_links/matches_links.py', '--cfg-path', '/var/folders/tp/ft4rfkmn1kz3dyw8hlfz1dxw0000gn/T/tmprc7tu_vo', '--error-file', '/var/folders/tp/ft4rfkmn1kz3dyw8hlfz1dxw0000gn/T/tmpn2jqtrr9']
[2021-05-17 09:18:41,193] {standard_task_runner.py:77} INFO - Job 7: Subtask get_autumn_nations_cup_links
[2021-05-17 09:18:41,219] {logging_mixin.py:104} INFO - Running <TaskInstance: matches_links.get_autumn_nations_cup_links 2021-04-24T10:00:00+00:00 [running]> on host Henrys-MacBook-Pro.local
[2021-05-17 09:18:41,241] {taskinstance.py:1281} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=matches_links
AIRFLOW_CTX_TASK_ID=get_autumn_nations_cup_links
AIRFLOW_CTX_EXECUTION_DATE=2021-04-24T10:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=backfill__2021-04-24T10:00:00+00:00
[2021-05-17 09:18:41,242] {bash.py:135} INFO - Tmp dir root location: 
 /var/folders/tp/ft4rfkmn1kz3dyw8hlfz1dxw0000gn/T
[2021-05-17 09:18:41,242] {bash.py:158} INFO - Running command: Rscript /Users/harry/rugby_data_project_airflow/R/scripts/create_matches_table.R  https://www.rugbypass.com/autumn-nations-cup/matches/
[2021-05-17 09:18:41,249] {bash.py:169} INFO - Output:
[2021-05-17 09:18:41,417] {bash.py:173} INFO - Error in args[2] %>% dmy : could not find function "%>%"
[2021-05-17 09:18:41,417] {bash.py:173} INFO - Execution halted
[2021-05-17 09:18:41,427] {bash.py:177} INFO - Command exited with return code 1
[2021-05-17 09:18:41,432] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/harry/.local/share/virtualenvs/rugby_data_project_airflow-d2RAFQI6/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/Users/harry/.local/share/virtualenvs/rugby_data_project_airflow-d2RAFQI6/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/Users/harry/.local/share/virtualenvs/rugby_data_project_airflow-d2RAFQI6/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/Users/harry/.local/share/virtualenvs/rugby_data_project_airflow-d2RAFQI6/lib/python3.8/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-05-17 09:18:41,435] {taskinstance.py:1525} INFO - Marking task as UP_FOR_RETRY. dag_id=matches_links, task_id=get_autumn_nations_cup_links, execution_date=20210424T100000, start_date=20210517T081841, end_date=20210517T081841
[2021-05-17 09:18:41,458] {local_task_job.py:146} INFO - Task exited with return code 1
[2021-05-17 09:25:47,405] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: matches_links.get_autumn_nations_cup_links 2021-04-24T10:00:00+00:00 [queued]>
[2021-05-17 09:25:47,410] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: matches_links.get_autumn_nations_cup_links 2021-04-24T10:00:00+00:00 [queued]>
[2021-05-17 09:25:47,411] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-17 09:25:47,411] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-05-17 09:25:47,411] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-17 09:25:47,415] {taskinstance.py:1089} INFO - Executing <Task(BashOperator): get_autumn_nations_cup_links> on 2021-04-24T10:00:00+00:00
[2021-05-17 09:25:47,417] {standard_task_runner.py:52} INFO - Started process 19117 to run task
[2021-05-17 09:25:47,423] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'matches_links', 'get_autumn_nations_cup_links', '2021-04-24T10:00:00+00:00', '--job-id', '3', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/matches_links/matches_links.py', '--cfg-path', '/var/folders/tp/ft4rfkmn1kz3dyw8hlfz1dxw0000gn/T/tmpo3jvqs09', '--error-file', '/var/folders/tp/ft4rfkmn1kz3dyw8hlfz1dxw0000gn/T/tmplqyctgh6']
[2021-05-17 09:25:47,424] {standard_task_runner.py:77} INFO - Job 3: Subtask get_autumn_nations_cup_links
[2021-05-17 09:25:47,455] {logging_mixin.py:104} INFO - Running <TaskInstance: matches_links.get_autumn_nations_cup_links 2021-04-24T10:00:00+00:00 [running]> on host Henrys-MacBook-Pro.local
[2021-05-17 09:25:47,478] {taskinstance.py:1281} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=matches_links
AIRFLOW_CTX_TASK_ID=get_autumn_nations_cup_links
AIRFLOW_CTX_EXECUTION_DATE=2021-04-24T10:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=backfill__2021-04-24T10:00:00+00:00
[2021-05-17 09:25:47,479] {bash.py:135} INFO - Tmp dir root location: 
 /var/folders/tp/ft4rfkmn1kz3dyw8hlfz1dxw0000gn/T
[2021-05-17 09:25:47,479] {bash.py:158} INFO - Running command: Rscript /Users/harry/rugby_data_project_airflow/R/scripts/create_matches_table.R  https://www.rugbypass.com/autumn-nations-cup/matches/ 2021-04-24
[2021-05-17 09:25:47,485] {bash.py:169} INFO - Output:
[2021-05-17 09:25:48,765] {bash.py:173} INFO - ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.0 ──
[2021-05-17 09:25:48,770] {bash.py:173} INFO - ✔ ggplot2 3.3.3     ✔ purrr   0.3.3
[2021-05-17 09:25:48,770] {bash.py:173} INFO - ✔ tibble  3.0.4     ✔ dplyr   1.0.2
[2021-05-17 09:25:48,770] {bash.py:173} INFO - ✔ tidyr   1.1.2     ✔ stringr 1.4.0
[2021-05-17 09:25:48,771] {bash.py:173} INFO - ✔ readr   1.3.1     ✔ forcats 0.5.0
[2021-05-17 09:25:48,844] {bash.py:173} INFO - ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
[2021-05-17 09:25:48,845] {bash.py:173} INFO - ✖ dplyr::filter() masks stats::filter()
[2021-05-17 09:25:48,845] {bash.py:173} INFO - ✖ dplyr::lag()    masks stats::lag()
[2021-05-17 09:25:48,854] {bash.py:173} INFO - 
[2021-05-17 09:25:48,855] {bash.py:173} INFO - Attaching package: ‘lubridate’
[2021-05-17 09:25:48,855] {bash.py:173} INFO - 
[2021-05-17 09:25:48,855] {bash.py:173} INFO - The following objects are masked from ‘package:base’:
[2021-05-17 09:25:48,855] {bash.py:173} INFO - 
[2021-05-17 09:25:48,856] {bash.py:173} INFO -     date, intersect, setdiff, union
[2021-05-17 09:25:48,856] {bash.py:173} INFO - 
[2021-05-17 09:25:48,857] {bash.py:173} INFO - Loading required package: xml2
[2021-05-17 09:25:48,864] {bash.py:173} INFO - 
[2021-05-17 09:25:48,865] {bash.py:173} INFO - Attaching package: ‘rvest’
[2021-05-17 09:25:48,865] {bash.py:173} INFO - 
[2021-05-17 09:25:48,865] {bash.py:173} INFO - The following object is masked from ‘package:purrr’:
[2021-05-17 09:25:48,865] {bash.py:173} INFO - 
[2021-05-17 09:25:48,866] {bash.py:173} INFO -     pluck
[2021-05-17 09:25:48,866] {bash.py:173} INFO - 
[2021-05-17 09:25:48,866] {bash.py:173} INFO - The following object is masked from ‘package:readr’:
[2021-05-17 09:25:48,866] {bash.py:173} INFO - 
[2021-05-17 09:25:48,867] {bash.py:173} INFO -     guess_encoding
[2021-05-17 09:25:48,867] {bash.py:173} INFO - 
[2021-05-17 09:25:48,869] {bash.py:173} INFO - Warning message:
[2021-05-17 09:25:48,870] {bash.py:173} INFO - All formats failed to parse. No formats found.
[2021-05-17 09:25:48,877] {bash.py:173} INFO - [1] "Getting autumn_nations_cup links"
[2021-05-17 09:25:50,979] {bash.py:173} INFO - [1] "autumn_nations_cup saved"
[2021-05-17 09:25:51,000] {bash.py:177} INFO - Command exited with return code 0
[2021-05-17 09:25:51,013] {taskinstance.py:1185} INFO - Marking task as SUCCESS. dag_id=matches_links, task_id=get_autumn_nations_cup_links, execution_date=20210424T100000, start_date=20210517T082547, end_date=20210517T082551
[2021-05-17 09:25:51,028] {taskinstance.py:1246} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-05-17 09:25:51,058] {local_task_job.py:146} INFO - Task exited with return code 0
